# Generated by Django 6.0.7 on 2026-07-30 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(help_text='Full job description text')),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('min_experience_years', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(default=0)),
                ('match_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('concerns', models.JSONField(blank=True, default=list)),
                ('analyzer_source', models.CharField(default='rule_based', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='candidates.candidate')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='jobs.jobdescription')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('experience', 'Experience-based'), ('project', 'Project-based')], max_length=20)),
                ('question', models.TextField()),
                ('rationale', models.CharField(blank=True, max_length=500)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.analysis')),
            ],
        ),
    ]
