services:
  - type: web
    name: job-portal-hr-system
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn hr_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "True"
      - key: AI_PROVIDER
        value: "none"
